name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit test
        run: docker build -t test -f Dockerfile.test .
